"""20230512190235

Revision ID: 59c1b5f9a187
Revises: 8bc64811769c
Create Date: 2023-05-12 12:02:37.201176

"""
import sqlalchemy as sa

# pylint: disable=no-member, invalid-name
from alembic import op

# revision identifiers, used by Alembic.
revision = "59c1b5f9a187"
down_revision = "8bc64811769c"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "model_framework", sa.Column("schema_url", sa.String(), nullable=False)
    )
    op.alter_column(
        "ontology_concept",
        "object_id",
        existing_type=sa.INTEGER(),
        type_=sa.String(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "ontology_concept",
        "object_id",
        existing_type=sa.String(),
        type_=sa.INTEGER(),
        existing_nullable=False,
    )
    op.drop_column("model_framework", "schema_url")
    # ### end Alembic commands ###
