"""
TDS equation Data Model Definition.
"""
from enum import Enum
from typing import Any, Optional

from pydantic import BaseModel, Field

from tds.db.base import BaseElasticSearchModel


class TypeEnum(str, Enum):
    """
    Equation Types Data Model
    Enumermation of mathml and latex equation types
    """

    MATHML: str = "MathML"
    LATEX: str = "LaTeX"


class EquationSource(BaseModel):
    """
    Equation Source Data Model
    """

    extracted_from: Optional[str] = Field(
        description="The document id of the source for the equation."
    )
    document_asset_name: Optional[str] = Field(
        description="The file name of the asset that represents the source for the equation."
    )
    hmi_generated: Optional[bool] = Field(
        description="Whether the equation was generated by the HMI."
    )


class Equation(BaseElasticSearchModel):
    """
    Equation Data Model
    """

    _index = "equation"

    username: str = Field(
        description="The username of the user that created the equation."
    )
    name: Optional[str] = Field(
        description="(Optional) Display/human name for the equation"
    )
    description: Optional[str] = Field(
        description="(Optional) Texual description of the equation"
    )
    equation_type: TypeEnum = Field(description="Type of equation (mathml or latex)")
    content: str = Field(description="String representation of the equation")
    metadata: Optional[dict[str, Any]] = Field(
        description="(Optional) Unformatted metadata about the equation"
    )
    source: Optional[EquationSource] = Field(
        description="(Optional) Source of equation, whether a document or HMI generated"
    )

    class Config:
        """
        equation Data Model Swagger Example
        """

        schema_extra = {
            "example": {
                "name": "SIDARTHE equation",
                "username": "Adam Smith",
                "description": "string",
                "timestamp": "2023-08-30T14:53:12.994Z",
                "equation_type": "latex",
                "metadata": {},
                "source": {
                    "extracted_from": "string",
                    "document_asset_name": "string",
                    "hmi_generated": False,
                },
                "content": "\\frac{dS}{dt} = - \\beta SI",
            }
        }
