# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


if !isdefined(@__MODULE__, :TaggableType)
    const TaggableType = String
else
    @warn("Skipping redefinition of TaggableType to String")
end
