# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""Run

    Run(;
        id=nothing,
        simulator_id=nothing,
        timestamp=nothing,
        completed_at=nothing,
        success=nothing,
        dataset_id=nothing,
        description=nothing,
        response=nothing,
        parameters=nothing,
    )

    - id::Int64
    - simulator_id::Int64
    - timestamp::ZonedDateTime
    - completed_at::ZonedDateTime
    - success::Bool
    - dataset_id::Int64
    - description::String
    - response::String
    - parameters::Vector{Any}
"""
Base.@kwdef mutable struct Run <: OpenAPI.APIModel
    id::Union{Nothing, Int64} = nothing
    simulator_id::Union{Nothing, Int64} = nothing
    timestamp::Union{Nothing, ZonedDateTime} = nothing
    completed_at::Union{Nothing, ZonedDateTime} = nothing
    success::Union{Nothing, Bool} = nothing
    dataset_id::Union{Nothing, Int64} = nothing
    description::Union{Nothing, String} = nothing
    response::Union{Nothing, String} = nothing
    parameters::Union{Nothing, Vector{Any}} = nothing

    function Run(id, simulator_id, timestamp, completed_at, success, dataset_id, description, response, parameters, )
        OpenAPI.validate_property(Run, Symbol("id"), id)
        OpenAPI.validate_property(Run, Symbol("simulator_id"), simulator_id)
        OpenAPI.validate_property(Run, Symbol("timestamp"), timestamp)
        OpenAPI.validate_property(Run, Symbol("completed_at"), completed_at)
        OpenAPI.validate_property(Run, Symbol("success"), success)
        OpenAPI.validate_property(Run, Symbol("dataset_id"), dataset_id)
        OpenAPI.validate_property(Run, Symbol("description"), description)
        OpenAPI.validate_property(Run, Symbol("response"), response)
        OpenAPI.validate_property(Run, Symbol("parameters"), parameters)
        return new(id, simulator_id, timestamp, completed_at, success, dataset_id, description, response, parameters, )
    end
end # type Run

const _property_types_Run = Dict{Symbol,String}(Symbol("id")=>"Int64", Symbol("simulator_id")=>"Int64", Symbol("timestamp")=>"ZonedDateTime", Symbol("completed_at")=>"ZonedDateTime", Symbol("success")=>"Bool", Symbol("dataset_id")=>"Int64", Symbol("description")=>"String", Symbol("response")=>"String", Symbol("parameters")=>"Vector{Any}", )
OpenAPI.property_type(::Type{ Run }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_Run[name]))}

function check_required(o::Run)
    true
end

function OpenAPI.validate_property(::Type{ Run }, name::Symbol, val)
    if name === Symbol("timestamp")
        OpenAPI.validate_param(name, "Run", :format, val, "date-time")
    end
    if name === Symbol("completed_at")
        OpenAPI.validate_param(name, "Run", :format, val, "date-time")
    end
    if name === Symbol("response")
        OpenAPI.validate_param(name, "Run", :format, val, "binary")
    end
end
