# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


if !isdefined(@__MODULE__, :OntologicalField)
    const OntologicalField = String
else
    @warn("Skipping redefinition of OntologicalField to String")
end
