# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.



@doc raw"""Id

    Id(; value=nothing)
"""
mutable struct Id <: OpenAPI.AnyOfAPIModel
    value::Any # Union{ Int64, String }
    Id() = new()
    Id(value) = new(value)
end # type Id

function OpenAPI.property_type(::Type{ Id }, name::Symbol, json::Dict{String,Any})
    
    # no discriminator specified, can't determine the exact type
    return fieldtype(Id, name)
end
