# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""create_software_external_software_post_201_response

    CreateSoftwareExternalSoftwarePost201Response(;
        id=nothing,
    )

    - id::Int64
"""
Base.@kwdef mutable struct CreateSoftwareExternalSoftwarePost201Response <: OpenAPI.APIModel
    id::Union{Nothing, Int64} = nothing

    function CreateSoftwareExternalSoftwarePost201Response(id, )
        OpenAPI.validate_property(CreateSoftwareExternalSoftwarePost201Response, Symbol("id"), id)
        return new(id, )
    end
end # type CreateSoftwareExternalSoftwarePost201Response

const _property_types_CreateSoftwareExternalSoftwarePost201Response = Dict{Symbol,String}(Symbol("id")=>"Int64", )
OpenAPI.property_type(::Type{ CreateSoftwareExternalSoftwarePost201Response }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_CreateSoftwareExternalSoftwarePost201Response[name]))}

function check_required(o::CreateSoftwareExternalSoftwarePost201Response)
    true
end

function OpenAPI.validate_property(::Type{ CreateSoftwareExternalSoftwarePost201Response }, name::Symbol, val)
end
