# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""create_feature_datasets_features_post_201_response

    CreateFeatureDatasetsFeaturesPost201Response(;
        id=nothing,
    )

    - id::Int64
"""
Base.@kwdef mutable struct CreateFeatureDatasetsFeaturesPost201Response <: OpenAPI.APIModel
    id::Union{Nothing, Int64} = nothing

    function CreateFeatureDatasetsFeaturesPost201Response(id, )
        OpenAPI.validate_property(CreateFeatureDatasetsFeaturesPost201Response, Symbol("id"), id)
        return new(id, )
    end
end # type CreateFeatureDatasetsFeaturesPost201Response

const _property_types_CreateFeatureDatasetsFeaturesPost201Response = Dict{Symbol,String}(Symbol("id")=>"Int64", )
OpenAPI.property_type(::Type{ CreateFeatureDatasetsFeaturesPost201Response }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_CreateFeatureDatasetsFeaturesPost201Response[name]))}

function check_required(o::CreateFeatureDatasetsFeaturesPost201Response)
    true
end

function OpenAPI.validate_property(::Type{ CreateFeatureDatasetsFeaturesPost201Response }, name::Symbol, val)
end
