# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""Publication

    Publication(;
        id=nothing,
        xdd_uri=nothing,
        title=nothing,
    )

    - id::Int64
    - xdd_uri::String
    - title::String
"""
Base.@kwdef mutable struct Publication <: OpenAPI.APIModel
    id::Union{Nothing, Int64} = nothing
    xdd_uri::Union{Nothing, String} = nothing
    title::Union{Nothing, String} = nothing

    function Publication(id, xdd_uri, title, )
        OpenAPI.validate_property(Publication, Symbol("id"), id)
        OpenAPI.validate_property(Publication, Symbol("xdd_uri"), xdd_uri)
        OpenAPI.validate_property(Publication, Symbol("title"), title)
        return new(id, xdd_uri, title, )
    end
end # type Publication

const _property_types_Publication = Dict{Symbol,String}(Symbol("id")=>"Int64", Symbol("xdd_uri")=>"String", Symbol("title")=>"String", )
OpenAPI.property_type(::Type{ Publication }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_Publication[name]))}

function check_required(o::Publication)
    o.xdd_uri === nothing && (return false)
    o.title === nothing && (return false)
    true
end

function OpenAPI.validate_property(::Type{ Publication }, name::Symbol, val)
end
