# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""Model

    Model(;
        id=nothing,
        name=nothing,
        description=nothing,
        framework=nothing,
        timestamp=nothing,
        state_id=nothing,
        concept=nothing,
        parameters=nothing,
        content=nothing,
    )

    - id::Int64
    - name::String
    - description::String
    - framework::String
    - timestamp::ZonedDateTime
    - state_id::Int64
    - concept::Concept
    - parameters::Vector{Any}
    - content::String
"""
Base.@kwdef mutable struct Model <: OpenAPI.APIModel
    id::Union{Nothing, Int64} = nothing
    name::Union{Nothing, String} = nothing
    description::Union{Nothing, String} = nothing
    framework::Union{Nothing, String} = nothing
    timestamp::Union{Nothing, ZonedDateTime} = nothing
    state_id::Union{Nothing, Int64} = nothing
    concept = nothing # spec type: Union{ Nothing, Concept }
    parameters::Union{Nothing, Vector{Any}} = nothing
    content::Union{Nothing, String} = nothing

    function Model(id, name, description, framework, timestamp, state_id, concept, parameters, content, )
        OpenAPI.validate_property(Model, Symbol("id"), id)
        OpenAPI.validate_property(Model, Symbol("name"), name)
        OpenAPI.validate_property(Model, Symbol("description"), description)
        OpenAPI.validate_property(Model, Symbol("framework"), framework)
        OpenAPI.validate_property(Model, Symbol("timestamp"), timestamp)
        OpenAPI.validate_property(Model, Symbol("state_id"), state_id)
        OpenAPI.validate_property(Model, Symbol("concept"), concept)
        OpenAPI.validate_property(Model, Symbol("parameters"), parameters)
        OpenAPI.validate_property(Model, Symbol("content"), content)
        return new(id, name, description, framework, timestamp, state_id, concept, parameters, content, )
    end
end # type Model

const _property_types_Model = Dict{Symbol,String}(Symbol("id")=>"Int64", Symbol("name")=>"String", Symbol("description")=>"String", Symbol("framework")=>"String", Symbol("timestamp")=>"ZonedDateTime", Symbol("state_id")=>"Int64", Symbol("concept")=>"Concept", Symbol("parameters")=>"Vector{Any}", Symbol("content")=>"String", )
OpenAPI.property_type(::Type{ Model }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_Model[name]))}

function check_required(o::Model)
    o.name === nothing && (return false)
    o.framework === nothing && (return false)
    true
end

function OpenAPI.validate_property(::Type{ Model }, name::Symbol, val)
    if name === Symbol("timestamp")
        OpenAPI.validate_param(name, "Model", :format, val, "date-time")
    end
    if name === Symbol("content")
        OpenAPI.validate_param(name, "Model", :format, val, "json-string")
    end
end
