# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.

module APIClient

using Dates, TimeZones
using OpenAPI
using OpenAPI.Clients

const API_VERSION = "0.3.10"

include("modelincludes.jl")

include("apis/api_ConceptsApi.jl")
include("apis/api_DatasetsApi.jl")
include("apis/api_ExperimentalApi.jl")
include("apis/api_ExternalApi.jl")
include("apis/api_GraphqlApi.jl")
include("apis/api_ModelsApi.jl")
include("apis/api_ParametersApi.jl")
include("apis/api_PersonsApi.jl")
include("apis/api_ProjectsApi.jl")
include("apis/api_ProvenanceApi.jl")
include("apis/api_SimulationsApi.jl")

end # module APIClient
