Project askem {
  database_type: 'PostgreSQL'
  Note: 'v3'
}

Enum public.resource_type {
   datasets
   models
   extractions
   plans
   intermediates
   publications
}

Enum relation_type {
  derivedfrom
  copiedfrom
  cites
  gluedFrom
  stratifiedFrom
  editedFrom
}

Enum taggable_type {
   features
   qualifiers
   datasets
   simulation_plans
   models
   model_parameters
   projects
   publications
   simulation_runs
}

Enum value_type {
  str
  int
  float
  bool
  binary
}

Enum ontological_field {
   unit
   obj
}

Enum intermediate_source {
  mrepresentationa
  skema
}

Enum intermediate_format {
  gromet
  bilayer
  sbml
  other
}

Enum public.role {
  author
  contributor
  maintainer
  other
}

Enum extracted_type {
   table
   figure
   equation
}

Enum direction {
  input
  output
}

Table dataset {
  id int [pk]
  name varchar [not null]
  url varchar [not null]
  description text [not null]
  timestamp datetime [default: `now()`, not null]
  deprecated bool
  sensitivity text
  quality text
  temporal_resolution varchar
  geospatial_resolution varchar
  annotations json
  maintainer int [not null, ref: > public.person.id]
}

Table feature {
  id int [pk]
  dataset_id int [ref: > dataset.id, not null]
  description text
  display_name varchar
  name varchar [not null]
  value_type value_type [not null]
}

Table qualifier {
  id int [pk]
  dataset_id int [ref: > dataset.id, not null]
  description text
  name varchar [not null]
  value_type value_type [not null]
}

Table qualifier_xref {
  id int [pk]
  qualifier_id int [ref: > qualifier.id, not null]
  feature_id int [ref: > feature.id, not null]
}

Table model_framework {
  name varchar [pk]
  version varchar [not null]
  semantics varchar [not null]
}

Table model {
  id int [pk]
  name varchar [not null]
  description text
  framework varchar [ref: > model_framework.name, not null]
  timestamp datetime [default: `now()`, not null]
  content json
}

Table intermediate {
  id int [pk]
  timestamp datetime [default: `now()`, not null]
  source intermediate_source [not null]
  type intermediate_format [not null]
  content blob [not null]
}

Table software {
  id int [pk]
  timestamp datetime [default:`now()`, not null]
  source varchar [not null, note: 'E.g. github url']
  storage_uri varchar [not null, note: 'E.g. S3 uri for zipfile of software']
}

Table model_runtime {
  id int [pk]
  timestamp datetime [default: `now()`, not null]
  name varchar [not null]
  left varchar [ref: > model_framework.name, not null]
  right varchar [ref: > model_framework.name, not null]
}

Table simulation_plan {
  id int [pk]
  model_id int [ref: > model.id, not null]
  simulator varchar [not null]
  query varchar [not null]
  content json [not null]
}

Table simulation_run {
  id int [pk]
  simulator_id int [ref: > simulation_plan.id, not null]
  timestamp datetime [default: `now()`, not null]
  completed_at datetime
  success bool
  response blob [note: 'The answer to the query whether its natural language or just a number.']
}

Table model_parameter {
  id int [pk]
  model_id int [ref: > model.id, not null]
  name varchar [not null]
  type value_type [not null]
  default_value varchar
}


Table simulation_parameter {
  id int [pk]
  run_id int [ref: > simulation_run.id, not null]
  name varchar [not null]
  value varchar [not null]
  type value_type [not null]
}

Table publication {
  id int [pk, note:"We cannot use the URI as a primary key due to the other asset using int types."]
  xdd_uri varchar [not null]
}

Table extraction {
  id int [pk]
  publication_id int [ref: > publication.id, not null]
  type extracted_type [not null]
  data blob [not null]
  img blob [not null]
}

Table project {
  id int [pk]
  name varchar [not null]
  description varchar [not null]
  timestamp datetime [default: `now()`]
  active bool [not null]
}

Table project_asset {
  id int [pk]
  project_id int [ref: > project.id, not null]
  resource_id int [not null]
  resource_type public.resource_type [not null]
  external_ref varchar [note:'The external resource that is pushed to on update']
}

Table ontology_concept {
  id int [pk]
  curie varchar [not null]
  type taggable_type [not null]
  object_id int [not null]
  status ontological_field [not null]
}

Table provenance {
  id int [pk]
  timestamp datetime [default: `now()`, not null]
  relation_type relation_type [not null]
  left int [not null]
  left_type resource_type [not null]
  right int [not null]
  right_type resource_type [not null]
  user_id int [ref: > person.id]
}

Table person {
  id int [pk]
  name varchar [not null]
  email varchar [not null]
  org varchar
  website varchar
  is_registered bool [not null, note: 'Individuals might be listed as a maintainer but may not be a registered user.']
}

Table association {
  id int [pk]
  person_id int [ref: > public.person.id, not null]
  resource_id int [not null]
  resource_type public.resource_type
  role public.role
}

