# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.

struct GraphqlApi <: OpenAPI.APIClientImpl
    client::OpenAPI.Clients.Client
end

"""
The default API base path for APIs in `GraphqlApi`.
This can be used to construct the `OpenAPI.Clients.Client` instance.
"""
basepath(::Type{ GraphqlApi }) = "http://localhost"

const _returntypes_handle_http_get_graphql_get_GraphqlApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => Any,
    Regex("^" * replace("404", "x"=>".") * "\$") => Nothing,
)

function _oacinternal_handle_http_get_graphql_get(_api::GraphqlApi; _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "GET", _returntypes_handle_http_get_graphql_get_GraphqlApi, "/graphql", [])
    OpenAPI.Clients.set_header_accept(_ctx, ["application/json", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? [] : [_mediaType])
    return _ctx
end

@doc raw"""Handle Http Get

Params:

Return: Any, OpenAPI.Clients.ApiResponse
"""
function handle_http_get_graphql_get(_api::GraphqlApi; _mediaType=nothing)
    _ctx = _oacinternal_handle_http_get_graphql_get(_api; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function handle_http_get_graphql_get(_api::GraphqlApi, response_stream::Channel; _mediaType=nothing)
    _ctx = _oacinternal_handle_http_get_graphql_get(_api; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

const _returntypes_handle_http_post_graphql_post_GraphqlApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => Any,
)

function _oacinternal_handle_http_post_graphql_post(_api::GraphqlApi; _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "POST", _returntypes_handle_http_post_graphql_post_GraphqlApi, "/graphql", [])
    OpenAPI.Clients.set_header_accept(_ctx, ["application/json", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? [] : [_mediaType])
    return _ctx
end

@doc raw"""Handle Http Post

Params:

Return: Any, OpenAPI.Clients.ApiResponse
"""
function handle_http_post_graphql_post(_api::GraphqlApi; _mediaType=nothing)
    _ctx = _oacinternal_handle_http_post_graphql_post(_api; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function handle_http_post_graphql_post(_api::GraphqlApi, response_stream::Channel; _mediaType=nothing)
    _ctx = _oacinternal_handle_http_post_graphql_post(_api; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

export handle_http_get_graphql_get
export handle_http_post_graphql_post
