FROM neo4j:latest 
# TODO: Use the postgres image directly instead of stateful install
RUN apt update 2> /dev/null
RUN apt install -y postgresql postgresql-contrib

COPY ./docker/scripts/start-neo4j.sh /entrypoint.sh
COPY ./docker/scripts/populate-cache.cypher /tmp/populate-cache.cypher

ENTRYPOINT ["/entrypoint.sh"]

