FROM neo4j:5.3.0
# TODO: Use the postgres image directly instead of stateful install
RUN apt update 2> /dev/null
RUN apt install -y postgresql postgresql-contrib netcat

ENV NEO4J_PLUGINS=[\"apoc\"]
ENV apoc.import.file.enabled=true

COPY ./docker/scripts/start-neo4j.sh /entrypoint.sh
COPY ./docker/scripts/populate-cache.cypher /tmp/populate-cache.cypher

ENTRYPOINT ["/entrypoint.sh"]

