"""Add documents to resourcetype enum

Revision ID: 2e5038df65a1
Revises: d28ca1c911be
Create Date: 2023-10-02 17:04:23.273477

"""
import sqlalchemy as sa

# pylint: disable=no-member, invalid-name
from alembic import op

# Elasticsearch operators such as es.create_index, es.remove_index, es.update_index_mapping, es.bulk_load_index_from_jsonl, etc
from migrations import es

# revision identifiers, used by Alembic.
revision = "2e5038df65a1"
down_revision = "d28ca1c911be"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

    #  Extra operations

    op.execute(sqltext="""ALTER TYPE resourcetype ADD VALUE 'documents';""")

    # ATTENTION: Enum type `taggabletype` cannot be automatically migrated!.
    # Current enum values in the database: (models, workflows, artifacts, simulation_parameters, model_configurations, publications, projects, datasets, code, qualifiers, simulations)
    # Enum definition in the code:         (models, artifacts, model_configurations, model_parameters, publications, projects, datasets, features, code, qualifiers, simulations)

    # Manual update of database --
    op.execute(
        sqltext="""
        DELETE from ontology_concept where type = 'workflows';
    """
    )
    op.execute(
        sqltext="""
        ALTER TYPE taggabletype RENAME TO old_taggabletype;
        CREATE TYPE taggabletype AS ENUM ('models', 'artifacts', 'model_configurations', 'model_parameters', 'publications', 'projects', 'datasets', 'features', 'code', 'qualifiers', 'simulations');
        ALTER TABLE ontology_concept ALTER COLUMN "type" SET DATA TYPE taggabletype USING type::text::taggabletype;
        DROP TYPE old_taggabletype;
    """
    )

    # End extra operations


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
