"""Sync DB with code

Revision ID: b3bdf1b266ff
Revises: f905fe63226c
Create Date: 2023-09-15 16:21:51.017177

"""
import sqlalchemy as sa

# pylint: disable=no-member, invalid-name
from alembic import op
from sqlalchemy.dialects import postgresql

# Elasticsearch operators such as es.create_index, es.remove_index, es.update_index_schema, es.bulk_load_index_from_jsonl, etc
from migrations import es

# revision identifiers, used by Alembic.
revision = "b3bdf1b266ff"
down_revision = "f905fe63226c"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("model_runtime")
    op.drop_table("extraction")
    op.alter_column(
        "association",
        "resource_id",
        existing_type=sa.INTEGER(),
        type_=sa.String(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "association",
        "resource_id",
        existing_type=sa.String(),
        type_=sa.INTEGER(),
        existing_nullable=False,
    )
    op.create_table(
        "extraction",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("publication_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "type",
            postgresql.ENUM("equation", "figure", "table", name="extractedtype"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("data", postgresql.BYTEA(), autoincrement=False, nullable=False),
        sa.Column("img", postgresql.BYTEA(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["publication_id"],
            ["publication.id"],
            name="extraction_publication_id_fkey",
        ),
        sa.PrimaryKeyConstraint("id", name="extraction_pkey"),
    )
    op.create_table(
        "model_runtime",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column(
            "timestamp",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("name", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("left", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("right", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["left"], ["model_framework.name"], name="model_runtime_left_fkey"
        ),
        sa.ForeignKeyConstraint(
            ["right"], ["model_framework.name"], name="model_runtime_right_fkey"
        ),
        sa.PrimaryKeyConstraint("id", name="model_runtime_pkey"),
    )
    # ### end Alembic commands ###
