"""Add provenance support for documents

Revision ID: b796846784ce
Revises: 2e5038df65a1
Create Date: 2023-10-20 20:20:28.817377

"""
import sqlalchemy as sa

# pylint: disable=no-member, invalid-name
from alembic import op

# Elasticsearch operators such as es.create_index, es.remove_index, es.update_index_mapping, es.bulk_load_index_from_jsonl, etc
from migrations import es

# revision identifiers, used by Alembic.
revision = "b796846784ce"
down_revision = "2e5038df65a1"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

    #  Extra operations

    op.execute(sqltext="""ALTER TYPE provenancetype ADD VALUE 'Document';""")

    # End extra operations


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
